<a href="https://colab.research.google.com/github/asdddddddddd/2025_KC_TI1B/blob/main/JOBSHEET2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JOBSHEET 2 :OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA


## Latihan 02 : Operasi matematika menggunakan python

a.	Mendapatkan nilai minimum dan maksimum

In [14]:
x = min (5, 10, 25)
y = max (6, 12, 18)
print(x)
print(y)

5
18


b.	Mendapatkan nilai absolut

In [15]:
x = abs (-7.25)
print(x)

7.25


c.	Mendapatkan nilai pangkat

In [16]:
import math
x = math.pow (4, 3)
print(x)

64.0


d.	Mendapatkan nilai akar

In [17]:
import math
x = math.sqrt (64)
print(x)

8.0


e.	Mendapatkan nilai pembulatan

In [18]:
import math
x = math.ceil (1.4)
y = math.floor (1.4)
print(x)
print(y)

2
1


f.	Mendapatkan nilai konstanta (PI)

In [19]:
import math
x = math.pi
print(x)

3.141592653589793


# Latihan 03 : Menggunakan Fungsi MATH

In [33]:
import math

print("math.sin(0):", math.sin(0))
print("math.cos(0):", math.cos(0))
print("math.tan(0):", math.tan(0))

print("math.log(10):", math.log(10))
print("math.log10(10):", math.log10(10))

print("math.degrees(math.pi):", math.degrees(math.pi))

print("math.dist([0,0], [3,4]):", math.dist([0, 0], [3, 4]))

print("math.factorial(5):", math.factorial(5))

print("math.fmod(10, 3):", math.fmod(10, 3))

print("math.isnan(float('nan')):", math.isnan(float('nan')))

print("math.gamma(6):", math.gamma(6))

print("math.perm(5, 2):", math.perm(5, 2))

math.sin(0): 0.0
math.cos(0): 1.0
math.tan(0): 0.0
math.log(10): 2.302585092994046
math.log10(10): 1.0
math.degrees(math.pi): 180.0
math.dist([0,0], [3,4]): 5.0
math.factorial(5): 120
math.fmod(10, 3): 1.0
math.isnan(float('nan')): True
math.gamma(6): 120.0
math.perm(5, 2): 20


# Latihan 04 : Operasi matriks dan vektor dengan python

a.	Membuat matriks di python

In [34]:
import numpy as np
A = np.array ([[80, 30, 25], [50, 20, 10]])
B = np.array ([[30, 60, 15], [10, 30, 30]])

hasil = A + B
print(hasil)

[[110  90  40]
 [ 60  50  40]]


b.	Melakukan operasi dot product

In [36]:
import numpy as np
A = np.array ([10, 20, 15])
B = np.array ([16, 67, 35])

hasil = np.dot (A, B)
print(hasil)

2025


c.	Melakukan operasi cross product

In [37]:
import numpy as np
A = np.array ([10, 20, 15])
B = np.array ([16, 67, 35])

hasil = np.cross(A, B)
print(hasil)

[-305 -110  350]


# Tugas Praktikum 01

In [41]:
import numpy as np

A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

hasil_AB = np.dot(A, B)
print("a. Hasil A x B:\n", hasil_AB)

hasil_BC = np.dot(B, C)
print("b. Hasil B x C:\n", hasil_BC)

a. Hasil A x B:
 [[7 2]
 [4 2]]
b. Hasil B x C:
 [[ 0  2  3]
 [-3  1  3]]


# Tugas Praktikum 02

In [43]:
import math

hasil_6_faktorial = math.factorial(6)
print("a. Hasil 6! =", hasil_6_faktorial)

hasil_8_per_5 = math.factorial(8) / math.factorial(5)
print("b. Hasil 8! / 5! =", hasil_8_per_5)


a. Hasil 6! = 720
b. Hasil 8! / 5! = 336.0


# Tugas Praktikum 03

In [44]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot_product = np.dot(A, B)

cross_product = np.cross(A, B)

print("Panjang Vektor A =", panjang_A)
print("Panjang Vektor B =", panjang_B)
print("Hasil A · B =", dot_product)
print("Hasil A × B =", cross_product)

Panjang Vektor A = 9.1104335791443
Panjang Vektor B = 12.409673645990857
Hasil A · B = 58
Hasil A × B = [ 24  79 -51]
